//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDG.PMAP.PublishingWebParts.BusinessHolidaysWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using MDG.PMAP.Common.Control;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.CodeDom.Compiler;
    
    
    public partial class BusinessHolidaysWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::MDG.PMAP.Common.Control.Link businessHolidaysApp;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(BusinessHolidaysWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::MDG.PMAP.Common.Control.Link @__BuildControlbusinessHolidaysApp() {
            global::MDG.PMAP.Common.Control.Link @__ctrl;
            @__ctrl = new global::MDG.PMAP.Common.Control.Link();
            this.businessHolidaysApp = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "businessHolidaysApp";
            @__ctrl.Location = global::MDG.PMAP.Common.Control.LocationType.Hive;
            @__ctrl.ScriptType = global::MDG.PMAP.Common.Control.LinkType.Script;
            @__ctrl.Href = "/_layouts/MDG.PMAP.PublishingWeb/App/Components/BusinessHolidays/BusinessHolidays" +
                "App.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::MDG.PMAP.PublishingWebParts.BusinessHolidaysWebPart.BusinessHolidaysWebPart @__ctrl) {
            global::MDG.PMAP.Common.Control.Link @__ctrl1;
            @__ctrl1 = this.@__BuildControlbusinessHolidaysApp();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n\r\n<script>\r\n    window.webSiteURL = \"");
                 @__w.Write( SPContext.Current.Site.Url );

            @__w.Write("\";\r\n    MdgCommon.hideLoader();\r\n</script>\r\n\r\n<div class=\"pmap-panel\" ng-app=\"pma" +
                    "pApp\">\r\n    <div class=\"panel\" ng-controller=\"businessHolidaysController as ctrl" +
                    "\">\r\n        <div class=\"panel-heading\">\r\n            <h1 class=\"panel-title\">Bus" +
                    "iness Holidays</h1>\r\n        </div>\r\n        <div class=\"bs-component panel-body" +
                    "\" ng-form=\"holidayForm\">\r\n            <div class=\"row\">\r\n                <div cl" +
                    "ass=\"col-sm-6\">\r\n                    <div class=\"form-group\">\r\n                 " +
                    "       <div class=\"col-sm-2\">\r\n                            <!--button type=\"butt" +
                    "on\" ng-click=\"ctrl.save(holidayForm)\">Add</button--> \r\n                         " +
                    "   <button type=\"button\" data-toggle=\"modal\" data-target=\"#businessHolidayDetail" +
                    "Modal\">Add</button>\r\n                        </div>\r\n                        <di" +
                    "v class=\"col-sm-2\">\r\n                                <button type=\"button\" ng-cl" +
                    "ick=\"ctrl.update()\">Update</button> \r\n                        </div>\r\n          " +
                    "              <div class=\"col-sm-3\">\r\n                                <button ty" +
                    "pe=\"button\" ng-click=\"ctrl.delete(ctrl.data.Id)\">Delete</button> \r\n             " +
                    "           </div>\r\n                    </div>\r\n                </div>\r\n         " +
                    "   </div>\r\n            <div class=\"row\">\r\n\r\n            </div>\r\n            <div" +
                    " class=\"row\">\r\n                <div class=\"tab-content\">\r\n                    <d" +
                    "iv class=\"tab-pane active\">\r\n                        <div class=\"col-md-12 table" +
                    "-responsive\">\r\n                            <table id  =\"ListData\" class=\"table t" +
                    "able-hover text-center\">\r\n                                    <thead>\r\n         " +
                    "                               <tr>\r\n                                           " +
                    " <th>Business Holiday Id\r\n\t\t\t\t\t\t\t\t                <span class=\"glyphicon sort-ic" +
                    "on\"></span>\r\n                                            </th>\r\n                " +
                    "                            <th>Holiday Date\r\n\t\t\t\t\t\t\t\t                <span clas" +
                    "s=\"glyphicon sort-icon\"></span>\r\n                                            </t" +
                    "h>\r\n                                            <th style=\"min-width: 130px;\">AC" +
                    "TION</th>                     \r\n                                        </tr>\r\n " +
                    "                               </thead>\r\n                                <tbody " +
                    "dir-paginate=\"holiday in ctrl.holidays|itemsPerPage:10\">\r\n                      " +
                    "              <tr ng-class=\"{active : ctrl.data.Id === holiday.Id}\">\r\n          " +
                    "                              <td ng-click=\"ctrl.view(holiday.Id,holiday.Holiday" +
                    "Date);\">{{holiday.Id}}</td>\r\n                                        <td ng-clic" +
                    "k=\"ctrl.view(holiday.Id,holiday.HolidayDate);\">{{ctrl.dateFormat(holiday.Holiday" +
                    "Date,\"MM/DD/YYYY\")}}</td>\r\n                                        <td>\r\n       " +
                    "                                         <a href=\"#\" class=\"btn btn-default btn-" +
                    "xs\" title=\"Post Activity\" ng-click=\"alert(\'test\')\" data-toggle=\"modal\" data-targ" +
                    "et=\"#productDetailModal\">\r\n                                                    <" +
                    "i class=\"fa fa-pencil-square-o\"></i>\r\n                                          " +
                    "      </a>\r\n                                                <a href=\"#\" ng-click" +
                    "=\"alert(\'test\')\" class=\"btn btn-default btn-xs\" title=\"Delete\">\r\n               " +
                    "                                     <i class=\"fa fa-trash\"></i>\r\n              " +
                    "                                  </a>\r\n                                        " +
                    "</td>\r\n                                    </tr>\r\n                              " +
                    "  </tbody>\r\n\r\n                         </table>\r\n                    </div>\r\n   " +
                    "                     <dir-pagination-controls\r\n                                m" +
                    "ax-size=\"5\"\r\n                                direction-links=\"true\"\r\n           " +
                    "                     boundary-links=\"true\" class=\"pull-right\">\r\n\t\t\t\t            " +
                    "    </dir-pagination-controls>\r\n                </div>\r\n             </div>\r\n   " +
                    "        </div>\r\n        </div>\r\n        <div class=\"modal fade\" id=\"businessHoli" +
                    "dayDetailModal\" role=\"dialog\" style=\"display: none;\">\r\n            <div class=\"m" +
                    "odal-dialog modal-lg\" role=\"document\">\r\n                <div class=\"modal-conten" +
                    "t\">\r\n                    <div class=\"modal-header\">\r\n                        <sp" +
                    "an class=\"fa fa-close fa-lg pull-right\" data-dismiss=\"modal\" aria-hidden=\"true\">" +
                    "</span>\r\n                        <h4 class=\"modal-title\">Holiday Date</h4>\r\n    " +
                    "                </div>\r\n                    <div class=\"modal-body\">\r\n          " +
                    "              <div ng-form=\"userForm\">\r\n                            <div class=\"" +
                    "row\">\r\n                                <div class=\"col-sm-12\">\r\n                " +
                    "                    <div class=\"form-group\">\r\n                                  " +
                    "      <div class=\"col-sm-3\">\r\n                                            <label" +
                    ">Holiday Date: *</label>\r\n                                        </div>\r\n      " +
                    "                                  <div class=\"col-sm-9\">\r\n                      " +
                    "                      <input type=\"text\" name=\"dtHolidayDate\" class=\"form-contro" +
                    "l disabled-text\" date-time required  ng-model=\"ctrl.data.HolidayDate\" min-view=\"" +
                    "date\" auto-close=\"true\" view=\"date\" maxlength=\"10\" format=\"MM/DD/YYYY\"/> \r\n     " +
                    "                                   </div>\r\n\r\n                                   " +
                    " </div>\r\n                                </div>\r\n                            </d" +
                    "iv>\r\n                        </div>\r\n                    </div>\r\n               " +
                    "     <div class=\"modal-footer\">\r\n                        <button type=\"button\" c" +
                    "lass=\"btn primary-button\" data-dismiss=\"modal\">Close</button>\r\n                 " +
                    "       <button type=\"button\" class=\"btn primary-button pull-right\" data-dismiss=" +
                    "\"modal\" ng-click=\"ctrl.save(userForm)\">Submit</button>\r\n                    </di" +
                    "v>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    \r\n    </div>" +
                    "\r\n</div>");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
