//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDG.PMAP.PublishingWebParts.EmailTemplateWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using MDG.PMAP.Common.Control;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.CodeDom.Compiler;
    
    
    public partial class EmailTemplateWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::MDG.PMAP.Common.Control.Link productsJS;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(EmailTemplateWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::MDG.PMAP.Common.Control.Link @__BuildControlproductsJS() {
            global::MDG.PMAP.Common.Control.Link @__ctrl;
            @__ctrl = new global::MDG.PMAP.Common.Control.Link();
            this.productsJS = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "productsJS";
            @__ctrl.Location = global::MDG.PMAP.Common.Control.LocationType.Hive;
            @__ctrl.ScriptType = global::MDG.PMAP.Common.Control.LinkType.Script;
            @__ctrl.Href = "/_layouts/MDG.PMAP.PublishingWeb/App/Components/EmailTemplate/emailTemplateApp.js" +
                "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::MDG.PMAP.PublishingWebParts.EmailTemplateWebPart.EmailTemplateWebPart @__ctrl) {
            global::MDG.PMAP.Common.Control.Link @__ctrl1;
            @__ctrl1 = this.@__BuildControlproductsJS();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n\r\n<script type=\"text/javascript\">\r\n    var webSiteURL = \"");
              @__w.Write( SPContext.Current.Web.Url );

            @__w.Write("\";\r\n</script>\r\n\r\n<div class=\"pmap-panel\" ng-app=\"pmapApp\">\r\n    <div class=\"panel" +
                    "\" ng-controller=\"emailTemplateController as ctrl\">\r\n        <div class=\"panel-he" +
                    "ading\">\r\n            <h1 class=\"panel-title\">Email Template</h1>\r\n        </div>" +
                    "\r\n        <div class=\"bs-component panel-body\">\r\n            <input type=\"button" +
                    "\" class=\"btn primary-button panel-create-btn\"  data-toggle=\"modal\" data-target=\"" +
                    "#productDetailModal\" value=\"Create New\" />\r\n            <div class=\"form-inline\"" +
                    ">\r\n                <div class=\"input-group input-group-sm pull-right raf-search\"" +
                    ">\r\n                    <span class=\"input-group-addon\"><i class=\"fa fa-search\"><" +
                    "/i></span>\r\n                    <input class=\"form-control\" placeholder=\"Search " +
                    "here...\" type=\"text\" ng-model=\"ctrl.filters.emailTemplate\">\r\n                </d" +
                    "iv>\r\n            </div>\r\n            <div style=\"clear: both;\">\r\n               " +
                    " <br />\r\n            </div>\r\n            <div class=\"tab-container\">\r\n          " +
                    "      <div class=\"tab-content\">\r\n                    <div class=\"tab-pane active" +
                    "\">\r\n                        <div class=\"col-md-12 raf-inprogress-table\">\r\n      " +
                    "                      <div class=\"table-responsive\">\r\n                          " +
                    "      <table class=\"raf-main-details-table table table-hover text-center\">\r\n    " +
                    "                                <thead>\r\n                                       " +
                    " <tr>\r\n                                            <th>TEMPLATE CODE</th>\r\n     " +
                    "                                       <th>SUBJECT</th>\r\n                       " +
                    "                     <th>BODY</th>\r\n                                        </tr" +
                    ">\r\n                                    </thead>\r\n                               " +
                    "     <tbody dir-paginate=\"template in ctrl.emailTemplate|filter: ctrl.emailTempl" +
                    "ateFilter|itemsPerPage:10\">\r\n                                        <tr>\r\n     " +
                    "                                       <td>{{template.TemplateCode}}</td>\r\n     " +
                    "                                       <td>{{template.Subject}}</td>\r\n          " +
                    "                                  <td>{{template.Body}}</td>\r\n                  " +
                    "                          <td>\r\n                                                " +
                    "<a href=\"#\" class=\"btn btn-default btn-xs\" title=\"Post Activity\" ng-click=\"ctrl." +
                    "loadProduct(\'\' + product.Id + \'\', productForm)\" data-toggle=\"modal\" data-target=" +
                    "\"#productDetailModal\">\r\n                                                    <i c" +
                    "lass=\"fa fa-pencil-square-o\"></i>\r\n                                             " +
                    "   </a>\r\n                                                <a href=\"#\" ng-click=\"c" +
                    "trl.delete(product.Id)\" class=\"btn btn-default btn-xs\" title=\"Delete\">\r\n        " +
                    "                                            <i class=\"fa fa-trash\"></i>\r\n       " +
                    "                                         </a>\r\n                                 " +
                    "           </td>\r\n                                        </tr>\r\n               " +
                    "                     </tbody>\r\n                                </table>\r\n       " +
                    "                     </div>\r\n                            <dir-pagination-control" +
                    "s\r\n                                max-size=\"5\"\r\n                               " +
                    " direction-links=\"true\"\r\n                                boundary-links=\"true\" c" +
                    "lass=\"pull-right\">\r\n\t\t\t\t                </dir-pagination-controls>\r\n            " +
                    "            </div>\r\n                    </div>\r\n                    <div class=\"" +
                    "clearfix\"></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n  " +
                    "      <div class=\"modal fade\" id=\"emailTemplateModal\" role=\"dialog\" style=\"displ" +
                    "ay: none;\">\r\n            <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n  " +
                    "              <div class=\"modal-content\">\r\n                    <div class=\"modal" +
                    "-header\">\r\n                        <span class=\"fa fa-close fa-lg pull-right\" da" +
                    "ta-dismiss=\"modal\" aria-hidden=\"true\"></span>\r\n                        <h4 class" +
                    "=\"modal-title\">Email Template</h4>\r\n                    </div>\r\n                " +
                    "    <div class=\"modal-body\">\r\n                        <div ng-form=\"productForm\"" +
                    ">\r\n                            <div class=\"row\">\r\n                              " +
                    "  <div class=\"col-sm-6\">\r\n                                    <div class=\"form-g" +
                    "roup\">\r\n                                        <div class=\"col-sm-3\">\r\n        " +
                    "                                    <label>Template Code: <span class=\"color-red" +
                    "\">*</span></label>\r\n                                        </div>\r\n            " +
                    "                            <div class=\"col-sm-9\">\r\n                            " +
                    "                <span class=\"pull-right warning-text\" ng-show=\"ctrl.toggles.name" +
                    "Limit\">{{100 - ctrl.data.Name.length}} characters remaining</span>\r\n            " +
                    "                                <input type=\"text\" name=\"Name\" class=\"form-contr" +
                    "ol\" ng-model=\"ctrl.data.Name\" required ng-required=\"true\" maxlength=\"100\"\r\n     " +
                    "                                           ng-focus=\"ctrl.toggles.nameLimit = tr" +
                    "ue\" ng-blur=\"ctrl.toggles.nameLimit = false\"/>\r\n                                " +
                    "            <span class=\"error-message\" ng-show=\"productForm.Name.$touched && pr" +
                    "oductForm.Name.$invalid\">This field is required or has invalid data.</span>\r\n   " +
                    "                                     </div>\r\n                                   " +
                    " </div>\r\n                                </div>\r\n                            </d" +
                    "iv>\r\n                            <div class=\"row\">\r\n                            " +
                    "    <div class=\"col-sm-6\">\r\n                                    <div class=\"form" +
                    "-group\">\r\n                                        <div class=\"col-sm-3\">\r\n      " +
                    "                                      <label>Subject: <span class=\"color-red\">*<" +
                    "/span></label>\r\n                                        </div>\r\n                " +
                    "                        <div class=\"col-sm-9\">\r\n                                " +
                    "            <span class=\"pull-right warning-text\" ng-show=\"ctrl.toggles.codeLimi" +
                    "t\">{{50 - ctrl.data.Code.length}} characters remaining</span>\r\n                 " +
                    "                           <input type=\"text\" name=\"Code\" class=\"form-control\" n" +
                    "g-model=\"ctrl.data.Code\" required ng-required=\"true\" maxlength=\"50\"\r\n           " +
                    "                                     ng-focus=\"ctrl.toggles.codeLimit = true\" ng" +
                    "-blur=\"ctrl.toggles.codeLimit = false\"/>\r\n                                      " +
                    "      <span class=\"error-message\" ng-show=\"productForm.Code.$touched && productF" +
                    "orm.Code.$invalid\">This field is required or has invalid data.</span>\r\n         " +
                    "                               </div>\r\n                                    </div" +
                    ">\r\n                                </div>\r\n                            </div>\r\n " +
                    "                           <div class=\"row\">\r\n                                <d" +
                    "iv class=\"col-sm-6\">\r\n                                    <div class=\"form-group" +
                    "\">\r\n                                        <div class=\"col-sm-3\">\r\n            " +
                    "                                <label>Email Body: <span class=\"color-red\">*</sp" +
                    "an></label>\r\n                                        </div>\r\n                   " +
                    "                     <div class=\"col-sm-9\">\r\n                                   " +
                    "         <span class=\"pull-right warning-text\" ng-show=\"ctrl.toggles.codeToGener" +
                    "ateLimit\">{{50 - ctrl.data.CodeToGenerate.length}} characters remaining</span>\r\n" +
                    "                                            <input type=\"text\" name=\"CodeToGener" +
                    "ate\" class=\"form-control\" ng-model=\"ctrl.data.CodeToGenerate\" maxlength=\"50\"\r\n  " +
                    "                                              ng-focus=\"ctrl.toggles.codeToGener" +
                    "ateLimit = true\" ng-blur=\"ctrl.toggles.codeToGenerateLimit = false\"/>\r\n         " +
                    "                               </div>\r\n                                    </div" +
                    ">\r\n                                </div>\r\n                            </div>\r\n " +
                    "                       </div>\r\n                    </div>\r\n                    <" +
                    "div class=\"modal-footer\">\r\n                        <button type=\"button\" class=\"" +
                    "btn primary-button\" data-dismiss=\"modal\" ng-click=\"ctrl.save(productForm)\" ng-di" +
                    "sabled=\"!ctrl.isFormValid()\">Submit</button>\r\n                        <button ty" +
                    "pe=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n        " +
                    "            </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n" +
                    "    </div>\r\n</div>");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
